### PR TITLE
 added a mechanism to change transaction fee

### PR DESCRIPTION
**Pull request by cpyberry**
Hello, I am cpyberry.
If you happen to have a free moment, I'd be very glad if you could give me your opinion.

## Issue

* #64

## Reasons

* This will be effective in resolving the issue

I wrote this mechanism with almost no changes to the existing implementation.
I used the function annotation for clarity, but it's different from the existing writing style, so I'll change it if you care about this.

### CODE REVIEW

**Comment by onuratakan** [comment]
We will write into the [Block Class](https://github.com/Decentra-Network/Decentra-Network/blob/master/src/blockchain/block/block_main.py#L45), because this configuration is dynamic, we will calculate the density every x block, and we will change in next block.

**Review by onuratakan — COMMENTED** [review]
We will write into the [Block Class](https://github.com/Decentra-Network/Decentra-Network/blob/master/src/blockchain/block/block_main.py#L45), because this configuration is dynamic, we will calculate the density every x block, and we will change in next block.

**Review by onuratakan — CHANGES_REQUESTED** [review]
-  We will add a element to [Block Class](https://github.com/Decentra-Network/Decentra-Network/blob/master/src/blockchain/block/block_main.py#L45)
- We will develop a system for calculate the density every x block, and change the transaction fee.
> Each node should make an evaluation according to its own pending transaction pool.
- We will change when we get the block
- We will change when we [get the block](https://github.com/Decentra-Network/Decentra-Network/blob/master/src/node/myownp2pn.py#L227)

**Comment by cpyberry** [comment]
I added a function on Block class to increase transaction fee by 0.01 DNC for each unit argument.

**Review by onuratakan — APPROVED** [review]

**Comment by onuratakan** [comment]
It will be Tested and Merge. Thanks

**Review by onuratakan — APPROVED** [review]
Good Job

**Pull request merged**
