### PR TITLE
Switching from pickle to json in the save system | Phase 1

### PR DESCRIPTION
**Pull request by onuratakan**
#15 
# Contents
Information and preliminary discourse about a switching process

# Reasons
Pickle is a simple but not useless model and these saves cannot be used in other languages.

# Solution
Systems except ledger switched to json save method

### CODE REVIEW

**Review by cpyberry — APPROVED** [review]
nice
This helps to switch from `pickle` to `json`

**Comment by TahaKty** [comment]
nice! it's work <3

**Comment by TahaKty** [comment]
nice! İt's work

**Review by TahaKty — APPROVED** [review]
vetry nice!! it's working

**Review by BySkyStorm — APPROVED** [review]
I did not see a problem,
Nice!

**Pull request merged**
