### PR TITLE
added functions to load and dump Account class with json

### PR DESCRIPTION
**Pull request by cpyberry**
Hello, I am cpyberry.
If you happen to have a free moment, I'd be very glad if you could give me your opinion.

## Contents

* added data to dump to sequence_number variable can also be saved
* I reverted the changes regarding ledger class
* I added sequence_number = 0 as an optional argument

## Reasons

* I have successfully saved and restored Account class
* I have confirmed that an error occurs when changing ledger class #19

## Pull request

This is a modification of this pull request
#19

### CODE REVIEW

**Comment by onuratakan** [comment]
Sequance Number must be zero or a stable number. Because all nodes must use the same number.

**Comment by onuratakan** [comment]
I will test your code as soon as possible. Thanks

**Comment by cpyberry** [comment]
Thank you, too

**Comment by cpyberry** [comment]
I changed the `load_json` function because the Account class now has two arguments

**Comment by onuratakan** [comment]
Sequance number is changeble but stable in creation the acount first time. Sequance number is increase after confirmed transaction. With this all transaction will confirmed one times.

**Review by onuratakan — APPROVED** [review]
Nice, thanks.

**Pull request merged**
