### PR TITLE
Made some changes to manage ledger in json

### PR DESCRIPTION
**Pull request by cpyberry**
Hello, I am cpyberry.
If you happen to have a free moment, I'd be very glad if you could give me your opinion.

## Contents

* added functions to load and dump Account class with json
* added functions to dump and save ledger class with json

## Issue

#15

After that, we can create a function to read ledger from the saved json

### CODE REVIEW

**Comment by cpyberry** [comment]
If you happen to have a free moment, check if there are issues

**Comment by onuratakan** [comment]
I will review it as soon as possible, thank you very much.

**Comment by onuratakan** [comment]
Hello i have reviewed your code, except for a few minor bugs, there are some problems. When we save it as json and then import it, the functions in our class structure cannot be used. In addition, I think we should use a fast database engine in the ledger system.

**Comment by cpyberry** [comment]
Thank you for your review.
When I tested it again I got an error in the ledger class.

In addition, I don't have one variable needed to restore the Acoount class.

**Pull request closed without merging**
